USE [master]
GO

/****** Object:  Database [coopeuch]    Script Date: 10/05/2021 14:59:18 ******/
CREATE DATABASE [coopeuch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'coopeuch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\coopeuch.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'coopeuch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\coopeuch_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [coopeuch] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [coopeuch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [coopeuch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [coopeuch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [coopeuch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [coopeuch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [coopeuch] SET ARITHABORT OFF 
GO

ALTER DATABASE [coopeuch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [coopeuch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [coopeuch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [coopeuch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [coopeuch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [coopeuch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [coopeuch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [coopeuch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [coopeuch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [coopeuch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [coopeuch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [coopeuch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [coopeuch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [coopeuch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [coopeuch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [coopeuch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [coopeuch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [coopeuch] SET RECOVERY FULL 
GO

ALTER DATABASE [coopeuch] SET  MULTI_USER 
GO

ALTER DATABASE [coopeuch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [coopeuch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [coopeuch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [coopeuch] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [coopeuch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [coopeuch] SET  READ_WRITE 
GO


USE [coopeuch]
GO

/****** Object:  Table [dbo].[Tarea]    Script Date: 10/05/2021 14:59:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Tarea](
	[id_identificador] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NOT NULL,
	[fecha_creacion] [datetime] NOT NULL,
	[vigente] [bit] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

